amazon:
  service: S3
  access_key_id: <%= Rails.application.credentials[Rails.env.to_sym][:aws][:access_key_id].presence %>
  secret_access_key: <%= Rails.application.credentials[Rails.env.to_sym][:aws][:secret_access_key].presence %>
  region: ap-northeast-1
  bucket: bumblebee-ap-northeast-1-860030201430

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>
